[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"
# Pass DATABASE_URL environment variable as a build argument
args = { DATABASE_URL = "${DATABASE_URL}" }

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicy = "on-failure"
restartPolicyMaxRetries = 10 